### ISSUE TITLE
User can search for a movie

### ISSUE THREAD

**Issue by Garcia-Tony** [Garcia-Tony/ScreenVerse#1]
## ⚙️ Feature

User can Search for any movie. 

## 📐 Functionality

The user will be able to type in the search bar and be able to receive data regarding the search request. 

## 🖼️ Wireframes

<img width="320" alt="Screen Shot 2024-09-03 at 7 24 23 PM" src="https://github.com/user-attachments/assets/9dce7ce1-3906-4ec9-a819-b87665d27a76">

<img width="983" alt="Screen Shot 2024-09-03 at 7 23 47 PM" src="https://github.com/user-attachments/assets/b3ca2c67-07c5-45ad-acbf-fcbcf8c7368f">

## ✅ Task List

- [x] Create the HTML for the webpage so it matches the figma example.
- [x] Make CSS for mobile devices first
- [x] Adjust styling to fluidly adapt to desktop.
- [x] Create the functionality for the search bar
- [x] Create the functionality for the search button to reload the page
- [x] In the search bar, the text cursor should be blinking
- [x] When user searches, data loads
- [x] When user searches, data loads in external page (local storage)
- [x] If no data available, No results message.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
-  [x] Test all functionality again in a private browsing session.
-  [x] Fix all errors.
 - [x] Check all code for proper formatting and indentation.
 - [x] Confirm that there are no errors in the console while using the application.
 - [x] Confirm that all previous functionality still works without errors.
