### ISSUE TITLE
User can add to watchlist

### ISSUE THREAD

**Issue by Garcia-Tony** [Garcia-Tony/ScreenVerse#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="164" alt="Screen Shot 2024-09-03 at 7 30 04 PM" src="https://github.com/user-attachments/assets/48dc65fb-04eb-4016-896e-486f840581ce">

<img width="502" alt="Screen Shot 2024-09-03 at 7 30 32 PM" src="https://github.com/user-attachments/assets/0868bc16-8c62-416d-8aab-43c4a00ea9aa">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML and CSS for star button
- [x] Make CSS for mobile devices first
- [x]  Adjust styling to fluidly adapt to desktop.
- [x] Create the functionality for the star button to activate
- [x] When star button activated, display css for pop-up message.
- [x] Create functionality for CLOSE button  
- [x] Create functionality for ADD button
- [x] Remove all CSS properties that have no effect.
 - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
